# Nom ......... : makefile
# Rôle ........ : compile dictionnaire
# Auteur ...... : Avrile Floro 
# Version ..... : V0.1 du 17/11/23
# Licence ..... : réalisé dans le cadre du cours d'Algo 1
# Usage : make 


all: compile 

compile:
	gcc -Wall dictionnaire.c category.c -o dictionnaire

clean:
	rm -f dictionnaire